from torch import Tensor
from ..utils._typing import _TN


def elliprc(x: _TN, y: _TN) -> Tensor: ...
def elliprd(x: _TN, y: _TN, z: _TN) -> Tensor: ...
def elliprf(x: _TN, y: _TN, z: _TN) -> Tensor: ...
def elliprg(x: _TN, y: _TN, z: _TN) -> Tensor: ...
def elliprj(x: _TN, y: _TN, z: _TN, p: _TN) -> Tensor: ...
