from typing import Sequence

from torch import Tensor

from ..utils._typing import _TN


def companion_matrix(*coeffs: Tensor) -> Tensor: ...
def vieta(rts: Sequence[Tensor]) -> Sequence[Tensor]: ...
def roots(*coeffs: _TN, force_numeric: bool = False) -> tuple[Tensor, ...]: ...
def sroots(*coeffs: _TN, dim: int = 0, force_numeric: bool = False) -> Tensor: ...
