from torch import Tensor


def elliprf(x: Tensor, y: Tensor, z: Tensor) -> Tensor: ...
def elliprc(x: Tensor, y: Tensor) -> Tensor: ...
def elliprj(x: Tensor, y: Tensor, z: Tensor, p: Tensor) -> Tensor: ...
def elliprd(x: Tensor, y: Tensor, z: Tensor) -> Tensor: ...
def elliprg(x: Tensor, y: Tensor, z: Tensor) -> Tensor: ...
