from torch import Tensor


def elliprf(x: Tensor, y: Tensor, z: Tensor) -> Tensor: ...
def elliprc(x: Tensor, y: Tensor) -> Tensor: ...
def elliprj(x: Tensor, y: Tensor, z: Tensor, p: Tensor) -> Tensor: ...
def elliprd(x: Tensor, y: Tensor, z: Tensor) -> Tensor: ...
def elliprg(x: Tensor, y: Tensor, z: Tensor) -> Tensor: ...

def ellipk(m: Tensor) -> Tensor: ...
def ellipe(m: Tensor) -> Tensor: ...
def ellipd(m: Tensor) -> Tensor: ...
def ellippi(n:Tensor, m: Tensor) -> Tensor: ...

def csc2(phi: Tensor) -> Tensor: ...

def ellipkinc_(c: Tensor, m: Tensor) -> Tensor: ...
def ellipeinc_(c: Tensor, m: Tensor) -> Tensor: ...
def ellipdinc_(c: Tensor, m: Tensor) -> Tensor: ...
def ellippiinc_(n: Tensor, c: Tensor, m: Tensor) -> Tensor: ...

def ellipkinc(phi: Tensor, m: Tensor) -> Tensor: ...
def ellipeinc(phi: Tensor, m: Tensor) -> Tensor: ...
def ellipdinc(phi: Tensor, m: Tensor) -> Tensor: ...
def ellippiinc(n: Tensor, phi: Tensor, m: Tensor) -> Tensor: ...
