from torch import Tensor


def roots2(b: Tensor, c: Tensor) -> tuple[Tensor, Tensor]: ...
def roots3(b: Tensor, c: Tensor, d: Tensor) -> tuple[Tensor, Tensor, Tensor]: ...
def roots4(b: Tensor, c: Tensor, d: Tensor, e: Tensor) -> tuple[Tensor, Tensor, Tensor, Tensor]: ...
