from abc import ABC

from .. import special
from ..core import FLRW
from ...utils._typing import _TN


class AbstractCosmology(FLRW, ABC):
    def lookback_time_dimless(self, z: _TN) -> _TN: ...
    def age_dimless(self, z: _TN) -> _TN: ...
    def absorption_distance_dimless(self, z: _TN) -> _TN: ...

class LambdaCDM(AbstractCosmology, special.LambdaCDM, ABC): ...
class LambdaCDMR(AbstractCosmology, special.LambdaCDMR, ABC): ...
class wCDM(AbstractCosmology, special.wCDM, ABC): ...
class wCDMR(AbstractCosmology, special.wCDMR, ABC): ...
class w0waCDM(AbstractCosmology, special.w0waCDM, ABC): ...
class w0waCDMR(AbstractCosmology, special.w0waCDMR, ABC): ...
class wpwaCDM(AbstractCosmology, special.wpwaCDM, ABC): ...
class wpwaCDMR(AbstractCosmology, special.wpwaCDMR, ABC): ...
class w0wzCDM(AbstractCosmology, special.w0wzCDM, ABC): ...
class w0wzCDMR(AbstractCosmology, special.w0wzCDMR, ABC): ...

class FlatLambdaCDM(AbstractCosmology, special.FlatLambdaCDM, ABC): ...
class FlatLambdaCDMR(AbstractCosmology, special.FlatLambdaCDMR, ABC): ...
class FlatwCDM(AbstractCosmology, special.FlatwCDM, ABC): ...
class FlatwCDMR(AbstractCosmology, special.FlatwCDMR, ABC): ...
class Flatw0waCDM(AbstractCosmology, special.Flatw0waCDM, ABC): ...
class Flatw0waCDMR(AbstractCosmology, special.Flatw0waCDMR, ABC): ...
class FlatwpwaCDM(AbstractCosmology, special.FlatwpwaCDM, ABC): ...
class FlatwpwaCDMR(AbstractCosmology, special.FlatwpwaCDMR, ABC): ...
class Flatw0wzCDM(AbstractCosmology, special.Flatw0wzCDM, ABC): ...
class Flatw0wzCDMR(AbstractCosmology, special.Flatw0wzCDMR, ABC): ...
